name: bid_and_shops
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  neopop: ^1.0.2
  localstorage: ^4.0.1+4
  provider: ^6.1.1
  dio: ^5.3.4
  font_awesome_flutter: ^10.6.0
  ionicons: ^0.2.2
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_contacts: ^1.1.7+1
  url_launcher: ^6.2.1
  onesignal_flutter: ^5.0.4
  permission_handler: ^11.0.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  animated_custom_dropdown_v2: ^1.5.0
  awesome_snackbar_content: ^0.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 600
    - family: Meer
      fonts:
        - asset: fonts/Merriweather-Light.ttf
        - asset: fonts/Merriweather-Light.ttf
          weight: 600
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

